[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]

[dependency-groups]
data-collection = [
    "cinemagoer",
    "kagglehub>=0.3.13",
]

[tool.uv.sources]
cinemagoer = { git = "https://github.com/cinemagoer/cinemagoer" }
